import React from 'react';
import LegalPage from './LegalPage';

export default function UserAgreement({ embedded = false }) {
  return (
    <LegalPage title="End User Terms of Use" embedded={embedded}>
      <p className="legal-subtitle">For Sales Representatives, Closers, and Authorized Users</p>
      <p className="legal-meta">Effective Date: April 14, 2026 | Last Updated: April 14, 2026</p>

      <hr />

      <h2>1. AGREEMENT TO TERMS</h2>
      <p>These End User Terms of Use (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and Kravok, operated by JAH Assets LLC, a Florida limited liability company (&ldquo;Kravok,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By downloading, installing, or using the Kravok application (the &ldquo;App&rdquo;), you agree to be bound by these Terms.</p>
      <p>You have been invited to use the App by your team leader, manager, or employer (your &ldquo;Organization&rdquo;). Your access to the App is provided through your Organization&rsquo;s subscription to the Kravok Platform. These Terms govern your individual use of the App.</p>
      <p>If you do not agree to these Terms, you may not use the App. We reserve the right to modify these Terms at any time. Material changes will be communicated through the App. Continued use of the App after such notice constitutes acceptance.</p>

      <h2>2. DESCRIPTION OF THE APP</h2>
      <p>Kravok is an AI-powered sales coaching and performance development platform. The App may include the following functionality:</p>
      <ul>
        <li><strong>Oracle</strong> &mdash; A real-time AI coaching copilot that processes audio from your sales calls to provide on-screen coaching suggestions, structured call notes, and performance scoring.</li>
        <li>Additional features as released from time to time.</li>
      </ul>
      <p>The App processes audio in real time for coaching purposes. Kravok does not store raw audio recordings. However, the App does generate and retain derivative data from your calls and training sessions, as described in Section 5.</p>

      <h2>3. YOUR ACCOUNT</h2>
      <p><strong>3.1 Access.</strong> Your access to the App is provided through your Organization&rsquo;s subscription. You may not share your login credentials with any other person. Your account is personal to you and may not be transferred.</p>
      <p><strong>3.2 Accuracy.</strong> You agree to provide accurate information when setting up your account and to keep your account information current.</p>
      <p><strong>3.3 Revocation.</strong> Your Organization may revoke your access to the App at any time. Kravok may also suspend or terminate your access if you violate these Terms.</p>

      <h2>4. CONSENT TO MONITORING AND PERFORMANCE TRACKING</h2>
      <p><strong>BY USING THE APP, YOU ACKNOWLEDGE AND CONSENT TO THE FOLLOWING:</strong></p>
      <p><strong>4.1 Audio Processing.</strong> When Oracle is active during a sales call, the App captures and processes audio from your microphone and system audio (both your voice and the other party&rsquo;s voice) in real time. This audio is processed to generate coaching suggestions, structured notes, and performance analytics. Raw audio is not stored by Kravok.</p>
      <p><strong>4.2 Performance Monitoring.</strong> The App generates detailed performance data about your sales calls and training activities, including but not limited to:</p>
      <ul>
        <li>Call performance scores and scorecards across multiple dimensions</li>
        <li>Talk-time ratios and behavioral analytics</li>
        <li>Coaching adherence metrics (whether you follow AI suggestions)</li>
        <li>Personality and communication style assessments</li>
        <li>Selling level analysis and behavioral pattern detection</li>
        <li>Training and simulation completion, scores, and progress</li>
        <li>Login activity and platform engagement</li>
        <li>Coachability scores and improvement trajectories</li>
      </ul>
      <p><strong>4.3 Manager Visibility.</strong> Your Organization&rsquo;s managers and administrators can see all of the performance data described above. This data is used by your Organization for coaching, performance management, training, and team development purposes.</p>
      <p><strong>4.4 Data Retention.</strong> Your performance data, scores, training records, and other analytics are retained by Kravok and remain associated with your Organization&rsquo;s account even after your access is revoked. Your historical data remains with your Organization and with Kravok.</p>
      <p><strong>4.5 Workplace Monitoring Laws.</strong> Your Organization is responsible for complying with all applicable workplace monitoring and employee privacy laws. If you have questions about how your Organization uses the data generated by the App, please contact your Organization directly.</p>

      <h2>5. DATA COLLECTION AND USAGE</h2>
      <p><strong>5.1 What We Collect.</strong> Through your use of the App, Kravok collects and generates the following types of data:</p>
      <ul>
        <li>Call transcripts (retained for a limited period, currently not exceeding 30 days)</li>
        <li>Structured call notes (pains, goals, objections, commitments, follow-up items, personal anecdotes, and other categories)</li>
        <li>Performance scores and scorecards</li>
        <li>Personality and behavioral assessments</li>
        <li>Training and simulation results</li>
        <li>Platform usage and engagement data</li>
        <li>Account information you provide</li>
      </ul>
      <p><strong>5.2 How We Use It.</strong> This data is used to provide real-time coaching and performance feedback, generate post-call scorecards and analytics, power training recommendations and skill development, provide your Organization with performance management tools, improve the Platform and develop new features, and create aggregated and anonymized benchmarks and analytics.</p>
      <p><strong>5.3 Third-Party Processing.</strong> Your data is processed through third-party service providers for functions including speech processing, artificial intelligence, voice synthesis, and infrastructure. These providers may change at any time. By using the App, you consent to your data being transmitted to and processed by our service providers.</p>
      <p><strong>5.4 Aggregated Data.</strong> Kravok may aggregate and anonymize data from your use of the App for purposes of improving the Platform, creating industry benchmarks, and conducting research. Aggregated data will not identify you personally.</p>
      <p><strong>5.5 Data Ownership.</strong> All data generated through the App &mdash; including transcripts, scores, analytics, and behavioral assessments &mdash; is owned by Kravok. You and your Organization are granted a license to access and use this data while your access is active, subject to these Terms and your Organization&rsquo;s Platform Terms of Service.</p>

      <h2>6. AUDIO PROCESSING AND RECORDING ACKNOWLEDGMENT</h2>
      <p><strong>6.1 Real-Time Processing.</strong> The App processes audio from sales calls in real time. This includes both your voice (captured via your microphone) and the other party&rsquo;s voice (captured via system audio). Raw audio is not stored. Derivative data (transcripts, notes, scores) is retained.</p>
      <p><strong>6.2 Your Responsibility.</strong> You acknowledge that you are responsible for complying with all applicable laws regarding the recording and monitoring of communications in your jurisdiction. In some jurisdictions, all parties to a call must consent to recording or monitoring. You are responsible for providing any required notice or obtaining any required consent from the other parties on your calls.</p>
      <p><strong>6.3 Kravok&rsquo;s Role.</strong> Kravok provides the processing technology but does not participate in your calls, does not contact the other parties, and is not responsible for any disclosures or consent required by applicable law.</p>

      <h2>7. AI-GENERATED CONTENT</h2>
      <p><strong>7.1 Nature of Suggestions.</strong> The App provides AI-generated coaching suggestions, objection handlers, pitch recommendations, and other content during and after sales calls. These suggestions are guidance only. They are not commands, directives, or guarantees.</p>
      <p><strong>7.2 Your Responsibility.</strong> You are solely responsible for what you say on your sales calls. AI suggestions may contain errors or may be inappropriate for a given situation. You must exercise your own judgment before using any AI-generated content. Kravok is not responsible for any consequences arising from your decision to follow or not follow AI suggestions.</p>
      <p><strong>7.3 No Professional Advice.</strong> AI-generated content does not constitute legal, financial, compliance, or professional advice. Any compliance-related alerts are informational tools only and do not replace qualified legal counsel.</p>

      <h2>8. ACCEPTABLE USE</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Share your login credentials with any other person.</li>
        <li>Attempt to reverse-engineer, decompile, or disassemble the App or any of its components.</li>
        <li>Attempt to circumvent or manipulate the App&rsquo;s scoring, anti-gaming, or performance tracking systems.</li>
        <li>Use the App to deceive, defraud, or manipulate prospects, customers, or any third party.</li>
        <li>Record, screenshot, or distribute any part of the App&rsquo;s interface, suggestions, or proprietary content without prior written consent from Kravok.</li>
        <li>Use the App in any manner that violates applicable law.</li>
        <li>Interfere with the App&rsquo;s performance, security, or infrastructure.</li>
      </ul>

      <h2>9. INTELLECTUAL PROPERTY</h2>
      <p>The App, including all software, AI models, algorithms, prompts, coaching methodologies, sales frameworks, user interfaces, and all related intellectual property, is and remains the sole and exclusive property of Kravok. You are granted a limited, non-exclusive, non-transferable, revocable license to use the App solely for the purpose of performing your role within your Organization and in accordance with these Terms. This license terminates immediately when your access is revoked.</p>

      <h2>10. DISCLAIMER OF WARRANTIES</h2>
      <p>THE APP IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. KRAVOK DOES NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
      <p>KRAVOK DOES NOT GUARANTEE ANY SPECIFIC SALES OUTCOMES, COMMISSION EARNINGS, OR CAREER RESULTS FROM YOUR USE OF THE APP.</p>

      <h2>11. LIMITATION OF LIABILITY</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KRAVOK SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE APP, INCLUDING BUT NOT LIMITED TO LOST COMMISSIONS, LOST EMPLOYMENT OPPORTUNITIES, OR DAMAGE TO YOUR PROFESSIONAL REPUTATION.</p>
      <p>KRAVOK&rsquo;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF THESE TERMS SHALL NOT EXCEED ONE HUNDRED DOLLARS (USD $100).</p>

      <h2>12. INDEMNIFICATION</h2>
      <p>You agree to indemnify and hold harmless Kravok, its officers, directors, employees, and affiliates from any claims, damages, losses, or expenses arising out of your use of the App, your violation of these Terms, your violation of any applicable law (including recording and monitoring laws), and any claims by third parties arising from your sales practices or communications.</p>

      <h2>13. TERM AND TERMINATION</h2>
      <p><strong>13.1 Term.</strong> These Terms are effective upon your acceptance and continue for as long as you have access to the App.</p>
      <p><strong>13.2 Termination.</strong> Your access may be revoked at any time by your Organization or by Kravok. Kravok may also terminate your access immediately if you violate these Terms.</p>
      <p><strong>13.3 Effect of Termination.</strong> Upon termination, your right to use the App ceases immediately. You must uninstall the App from all devices. Your historical performance data remains with your Organization and with Kravok as described in Section 4.4. Provisions regarding data ownership, intellectual property, indemnification, limitation of liability, and any other provisions that by their nature should survive, will survive termination.</p>

      <h2>14. PRIVACY</h2>
      <p>Your use of the App is governed by the Kravok Privacy Policy. Please review the Privacy Policy for detailed information about how we collect, use, and protect your data. If you are located outside the United States, you acknowledge that your data may be transferred to and processed in the United States and other jurisdictions.</p>

      <h2>15. DISPUTE RESOLUTION</h2>
      <p><strong>15.1 Governing Law.</strong> These Terms shall be governed by the laws of the State of Florida without regard to conflict of laws principles.</p>
      <p><strong>15.2 Arbitration.</strong> Any dispute arising under these Terms shall be resolved through binding arbitration administered in the State of Florida in accordance with the rules of the American Arbitration Association.</p>
      <p><strong>15.3 Class Action Waiver.</strong> You agree that any dispute will be resolved on an individual basis and not as part of any class, consolidated, or representative action.</p>

      <h2>16. ELIGIBILITY</h2>
      <p>You must be at least eighteen (18) years old to use the App. By using the App, you represent that you meet this requirement.</p>

      <h2>17. MISCELLANEOUS</h2>
      <p><strong>17.1 Entire Agreement.</strong> These Terms constitute the entire agreement between you and Kravok with respect to your use of the App.</p>
      <p><strong>17.2 Severability.</strong> If any provision is held invalid, the remaining provisions continue in full force.</p>
      <p><strong>17.3 No Waiver.</strong> Failure to enforce a provision does not constitute a waiver.</p>
      <p><strong>17.4 Contact.</strong> For questions about these Terms, contact us at support@kravok.ai.</p>

      <hr />

      <p className="legal-acceptance"><strong>BY CLICKING &ldquo;I AGREE&rdquo; OR BY DOWNLOADING, INSTALLING, OR USING THE APP, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS.</strong></p>
    </LegalPage>
  );
}
